#!/usr/bin/env bash
# Installs, configures, and starts the server
apt-get update
apt-get -y install nginx

mkdir -p /var/www/html
touch /var/www/html/index.html
echo "Hello World!" > /var/www/html/index.html
touch /var/www/html/404.html

printf %s "server {
    listen 80;
    listen [::]:80;
    root   /var/www/html;
    index  index.html index.htm;

    location /redirect_me {
        return 301 http://www.youtube.com/watch?v=QH2-TGUlwu4;
    }

    error_page 404 /404.html;
    location /404 {
      root /var/www/html;
      internal;
    }
}" > /etc/nginx/sites-available/default

service nginx restart
